### ISSUE TITLE
File Manager upload directory

### ISSUE THREAD

**Issue by Cherry** [nodecraft/customer-suggestions#17]
When uploading files to the file manager under certain conditions, they may land in a previously accessed directory, rather than the current one.

**Comment by blazedd** [comment]
The problem was that we were not de-constructing the uploader before re-initializing another instance in  between page loads. This means if we change page to the console or any other Angular controller we would be changing the scope of the upload.

This has been fixed by updating our upload service with a returned destroy function and hooking into the scope $destroy event.
